name: Format and Lint

on:
  workflow_call:

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --only-group dev --frozen

      - name: Run Linters
        run: uv run make lint
