name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_target: [ui-test e2e-test]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Run tests
        run: uv run make ${{ matrix.test_target }}
